.\" This Source Code Form is subject to the terms of the Mozilla Public
.\" License, v. 2.0. If a copy of the MPL was not distributed with this
.\" file, You can obtain one at http://mozilla.org/MPL/2.0/.
.\"
.\" Copyright (c) 2016 David Jackson
.\"
.Dd June 26, 2016
.Dt CTACHE_RENDER 3
.Os
.Sh NAME
.Nm ctache_render_string, ctache_render_file
.Nd render mustache-style templates
.Sh LIBRARY
.Lb libctache
.Sh SYNOPSIS
.In ctache/ctache.h
.Ft void
.Fo ctache_render_string
.Fa "const char *in_str" "size_t in_str_len" "FILE *out_fp" "ctache_data_t *data" "enum escaping_type escaping_type" "const char *delim_begin" "const char *delim_end"
.Fc
.Ft void
.Fo ctache_render_file
.Fa "FILE *in_fp" "FILE *out_fp" "ctache_data_t *data" "enum escaping_type escaping_type" "const char *delim_begin" "const char *delim_end"
.Fc
.Sh DESCRIPTION
The ctache_render family of functions is used to render a mustache-style
template using data in a ctache_data_t format. The ctache_render_string()
function renders a template in string form, whereas the ctache_render_file()
function render a template directly from a file pointer.
.Pp
The delim_ arguments are used to specify the begining and ending delimiters
for tags. By default these are "{{" and "}}", respectively.
