.Dd June 26, 2016
.Dt CTACHE_RENDER 3
.Os
.Sh NAME
.Nm ctache_render_string, ctache_render_file
.Nd render mustache-style templates
.Sh LIBRARY
.Lb libctache
.Sh SYNOPSIS
.In ctache.h
.Ft void
.Fo ctache_render_string
.Fa "const char *in_str" "size_t in_str_len" "FILE *out_fp" "ctache_data_t *data" "int flags" "enum escaping_type escaping_type"
.Fc
.Ft void
.Fo ctache_render_file
.Fa "FILE *in_fp" "FILE *out_fp" "ctache_data_t *data" "int flags" "enum escaping_type escaping_type"
.Fc
.Sh DESCRIPTION
The ctache_render family of functions is used to render a mustache-style
template using data in a ctache_data_t format. The ctache_render_string()
function renders a template in string form, whereas the ctache_render_file()
function render a template directly from a file pointer.
